My initial commit for Babis
BornToBeCool/gitTest pull request #1
Opened 2021-09-09 18:07 UTC by BornToBeCool

2021-09-09 18:12 UTC, bkyf commented on test.py
> +print("hello World!")
This is useless, delete this file.

2021-09-13 14:53 UTC, bkyf requested changes
check these out and let me know

2021-09-13 14:53 UTC, bkyf commented on main.py
> +    runGame()
Not really a point here to have an empty main, with only one call. The class run could simply be in main.

2021-09-13 14:53 UTC, bkyf commented on run.py
> +        if (len(game.teams[0].alive_heroes) == 0 or len(game.teams[1].alive_heroes) == 0):
This condition could had simply had been in the while loop. The while does have a condition that could take the condition you have in the `if ` here

2021-09-13 14:53 UTC, bkyf commented on game.py
> +            for i in heroe_list:
small comment, instead of i you could have named the variable `heroe`

2021-09-13 14:53 UTC, bkyf commented on game.py
> +            all_heroes.remove(random_choice)
That's really good, well done for thinking about that!

2021-09-13 14:53 UTC, bkyf commented on game.py
> +        random_heroes = self.random_heroes()
Why do you need that? it is not a random choice mode

2021-09-13 14:53 UTC, bkyf commented on game.py
> +
delete empty spaces

2021-09-13 14:53 UTC, bkyf commented on game.py
> +
A comment on what is the purpose of that will help

2021-09-13 14:53 UTC, bkyf commented on game.py
> +        for i in list_heroe_names:
instead of `i` you could name the var `name`

2021-09-13 14:53 UTC, bkyf commented on game.py
> +                user_choice = int(input("Select one of the above heroes: "))
this `input` will be displayed again, after the user makes a selection as after this line the code will go to line 99 again...

2021-09-13 14:53 UTC, bkyf commented on game.py
> +            counter += 1
This is a wrong place to increase the counter. The counter increases even if I select a wrong number!!

2021-09-13 14:53 UTC, bkyf commented on game.py
> +
delete the empty spaces

2021-09-13 14:53 UTC, bkyf commented on game.py
> +    def calculate_damages(self, teamA , teamB, x):
it may be better to name them team1 and team2 here, as some times teamA may actually be teamB

2021-09-13 14:53 UTC, bkyf commented on game.py
> +                if heroe_damage_amount[0] == "heal":
in order to make the code a bit cleaner here, you may want to use `switch` instead of `if/elif/else` here. 
Have a look at that:
[https://pythongeeks.org/switch-in-python/](url)

2021-09-13 14:53 UTC, bkyf commented on game.py
> +        self.show_damages(team_damages,x)
x is not a good name for a variable, find a better one

2021-09-13 14:53 UTC, bkyf commented on game.py
> +        self.show_damages(team_damages,x)
maybe something like "activeTeam"??

2021-09-13 14:53 UTC, bkyf commented on game.py
> +    def game_round(self,):
rename it to increase_game_round

2021-09-13 14:53 UTC, bkyf commented on heroes.py
> +    def heal_or_damage_or_stun(self,):
This method is useless, it just calls and returns another method. Just call the other method and you are done

2021-09-13 14:53 UTC, bkyf commented on heroes.py
> +        self.max_health += + (self.base_health * 0.1 * self.level)
you can calculate `(self.base_health * 0.1 * self.level)` once, store it in a var and use the var for both.

2021-09-13 14:53 UTC, bkyf commented on team.py
> +        random_heroe.current_health -= amount
it is safer to use a method in the heroe class to do that, instead of changing this value in here

2021-09-13 14:53 UTC, bkyf commented on team.py
> +        random_heroe.current_health += amount
same here

2021-09-13 14:53 UTC, bkyf commented on team.py
> +    def check_heroes_health(self,):
again, it is useless to have a method that its only purpose is to call another method

2021-09-13 14:53 UTC, bkyf commented on team.py
> +        while i < len(self.alive_heroes):
I am not sure, but you probably could had done the same thing using 
```
for index, heroe in enumerate(self.alive_heroes):
if heroe.current_health <= 0:
                self.dead_heroes.append(heroe)
                self.alive_heroes.remove(heroe) ##__OR__## self.alive_heroes.pop(index)
```

2021-09-13 14:53 UTC, bkyf commented on team.py
> +            lowest_health = self.alive_heroes[0]
By `lowest_health` I thought the value of the health, whereas you are taking the whole hero; Hence better rename it to `hero_with_lowest_health` or something that indicates you hold a hero in this variable

2021-09-15 13:45 UTC, BornToBeCool commented on test.py
> +print("hello World!")
Done

2021-09-15 15:05 UTC, BornToBeCool commented on run.py
> +        if (len(game.teams[0].alive_heroes) == 0 or len(game.teams[1].alive_heroes) == 0):
Tried to use (len(game.teams[0].alive_heroes) > 0 or len(game.teams[1].alive_heroes) > 0): in the While condition, but i am getting a syntax error.

2021-09-15 15:07 UTC, BornToBeCool commented on game.py
> +            for i in heroe_list:
Changed the variable name from i to heroe

2021-09-15 15:07 UTC, BornToBeCool commented on game.py
> +            all_heroes.remove(random_choice)
Cheers :)

2021-09-15 15:13 UTC, BornToBeCool commented on game.py
> +        random_heroes = self.random_heroes()
The self.random_heroes() function returns 10 random heroes. 
So the name random_heroes means that the heroes that was selected are random from the CSV file.

2021-09-15 15:15 UTC, BornToBeCool commented on team.py
> +        random_heroe.current_health -= amount
I agree, but i followed  the PDF description.

2021-09-15 15:15 UTC, BornToBeCool commented on team.py
> +        random_heroe.current_health += amount
I agree, but i followed the PDF description.

2021-09-15 15:20 UTC, BornToBeCool commented on team.py
> +    def check_heroes_health(self,):
Fixed.

2021-09-15 15:23 UTC, BornToBeCool commented on team.py
> +            lowest_health = self.alive_heroes[0]
Thanks, changed the variable name to hero_with_lowest_health

2021-09-15 15:45 UTC, BornToBeCool commented on game.py
> +
Done

2021-09-15 15:47 UTC, BornToBeCool commented on team.py
> +        while i < len(self.alive_heroes):
Thanks

2021-09-15 15:50 UTC, bkyf commented on run.py
> +        if (len(game.teams[0].alive_heroes) == 0 or len(game.teams[1].alive_heroes) == 0):
try `while len(game.teams[0].alive_heroes) > 0 or len(game.teams[1].alive_heroes) > 0:

2021-09-15 15:50 UTC, bkyf commented on team.py
> +        random_heroe.current_health -= amount
can you change it please?

2021-09-15 15:51 UTC, bkyf commented on team.py
> +        random_heroe.current_health += amount
same as above

2021-09-22 11:01 UTC, BornToBeCool commented on run.py
> +        if (len(game.teams[0].alive_heroes) == 0 or len(game.teams[1].alive_heroes) == 0):
Tried this: while len(game.teams[0].alive_heroes) > 0 or len(game.teams[1].alive_heroes) > 0: but i am getting an index error. I think i need to go much deeper to find the problem. I am gonna let it like that for now. I might need you help about this one.

2021-09-22 11:12 UTC, BornToBeCool commented on game.py
> +        for i in list_heroe_names:
Update i to name

2021-09-22 11:18 UTC, BornToBeCool commented on game.py
> +
The i is the whole list with the heroe stats. The index 0 is the name. So actually i am appending only the names into the list list_heroe_names = [].

2021-09-22 11:27 UTC, BornToBeCool commented on game.py
> +                user_choice = int(input("Select one of the above heroes: "))
Deleted the line 102.

2021-09-22 11:37 UTC, BornToBeCool commented on game.py
> +                user_choice = int(input("Select one of the above heroes: "))
Updated the if statement with While loop.

2021-09-22 11:38 UTC, BornToBeCool commented on game.py
> +            counter += 1
Updated the if statement with while loop, so the counter wont increase when the selection will be incorrect.

2021-09-22 11:39 UTC, BornToBeCool commented on game.py
> +
Done

2021-09-22 11:44 UTC, BornToBeCool commented on game.py
> +    def calculate_damages(self, teamA , teamB, x):
Changed teamA to team1 and teamB to team2.

2021-09-22 11:45 UTC, BornToBeCool commented on game.py
> +        self.show_damages(team_damages,x)
Active team sounds good. Updated to ActiveTeam.

2021-09-22 11:49 UTC, BornToBeCool commented on game.py
> +    def game_round(self,):
Updated to increase_game_round

2021-09-22 12:52 UTC, merged